name: Load Test

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main # Adjust as needed

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install k6
      run: |
        sudo apt update
        sudo apt install -y k6

    - name: Run Load Test
      run: |
        k6 run tests/load-test.js
